export const COMMON_UPDATE_PARENT_TASKS = 'COMMON_UPDATE_PARENT_TASKS';
export const COMMON_SET_TASK_CONSTRAINTS = 'COMMON_SET_TASK_CONSTRAINTS';
export const COMMON_SET_TASK_VARIANCES = 'COMMON_SET_TASK_VARIANCES';
export const COMMON_GET_PROJECT_MATERIALS = 'COMMON_GET_PROJECT_MATERIALS';
export const COMMON_CLEAR_PROJECT_MATERIALS = 'COMMON_CLEAR_PROJECT_MATERIALS';
export const COMMON_GET_PROJECT_TASK_MATERIALS =
  'COMMON_GET_PROJECT_TASK_MATERIALS';
export const COMMON_CLEAR_PROJECT_TASK_MATERIALS =
  'COMMON_CLEAR_PROJECT_TASK_MATERIALS';
export const COMMON_DELETE_PROJECT_TASK_MATERIAL =
  'COMMON_DELETE_PROJECT_TASK_MATERIAL';
export const COMMON_UPDATE_PROJECT_TASK_MATERIAL =
  'COMMON_UPDATE_PROJECT_TASK_MATERIAL';
export const COMMON_GET_CUSTOM_LIST = 'COMMON_GET_CUSTOM_LIST';
export const COMMON_CLEAR_EDIT_PROJECT_PLAN_STATE =
  'COMMON_CLEAR_EDIT_PROJECT_PLAN_STATE';
export const COMMON_GET_RELATED_TASKS = 'COMMON_GET_RELATED_TASKS';
export const COMMON_SET_CURRENT_TASK = 'COMMON_SET_CURRENT_TASK';
export const COMMON_SET_PROJECT_TOKEN = 'COMMON_SET_PROJECT_TOKEN';

export const COMMON_SET_LOOKAHEAD_ACTION = 'COMMON_SET_LOOKAHEAD_ACTION';
export const COMMON_GET_TENANT_COMPANIES_LIST =
  'COMMON_GET_TENANT_COMPANIES_LIST';
export const GET_ATTACHMENT_FILES = 'GET_ATTACHMENT_FILES';
export const SET_UPLOADED_FILES = 'SET_UPLOADED_FILES';
export const CLEAR_UPLOADED_FILES = 'CLEAR_UPLOADED_FILES';
