import { Grid } from '@material-ui/core';
import React, { ReactElement, useContext } from 'react'
import { templateCreationContext } from '../../context/templateCreation/context';
import './AutoGeneratedFields.scss'


function AutoGeneratedFields(props: any): ReactElement {
    return (
        <div className='AutoGeneratedFields'>
            <div className='AutoGeneratedFields__name'>Auto Generated Fields:</div>
            <Grid container className='AutoGeneratedFields__list'>
                {props.autoGeneratedFields.map((item: any)=>(
                    <Grid item xs={3} className='AutoGeneratedFields__list__item' key={item.elementId}>
                            <div className='AutoGeneratedFields__list__item__name'> {item.caption}: </div>
                            <span>--</span>
                    </Grid>
                ))}
            </Grid>
        </div>
    )
}

export default AutoGeneratedFields
