import { FormFieldData } from "../../components/layer2/Forms/modals/form";


export const intializeFormFieldData = (item: any): FormFieldData => {
    return {
      autoGenerated: item.autoGenerated,
      caption: item.caption,
      configListId: item.configListId,
      elementId: item.elementId,
      fieldTypeId: item.fieldTypeId,
      fixed: item.fixed,
      required: item.required,
      sequence: item.sequence,
    //   width: item.fieldTypeId == InputType.TABLE ? 100 : item.width,
    width: item.fieldTypeId == 18 ? 100 : item.width,
      tableId: item.tableId || null,
      metaData: item?.metadata || [],
      filterable: item?.filterable,
    };
  };