export const CLEAR_RECIPE_TASK_STATE = 'CLEAR_RECIPE_TASK_STATE';

export const UPDATE_PARENT_TASKS = 'UPDATE_PARENT_TASKS';

export const GET_ALL_TENANT_MATERIAL = 'GET_ALL_TENANT_MATERIAL';
export const GET_RECIPE_TASK_MATERIAL = 'GET_RECIPE_TASK_MATERIAL';
export const UPDATE_RECIPE_MATERIAL = 'UPDATE_RECIPE_MATERIAL';
export const DELETE_RECIPE_MATERIAL = 'DELETE_RECIPE_MATERIAL';
export const CLEAR_EDIT_RECIPE_TASK_STATE = 'CLEAR_EDIT_RECIPE_TASK_STATE';
