export const RECIPE_DETAILS = 'RECIPE_DETAILS';
export const SET_RECIPE_PLAN = 'SET_RECIPE_PLAN';
export const CACHE_TASKS = 'CACHE_TASKS';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_METADATA = 'SET_METADATA';
export const SET_DELETE_TASK_ID = 'SET_DELETE_TASK_ID';
export const SET_NAVIGATING_STATUS = 'SET_NAVIGATING_STATUS';
