export const GET_EQUIPMENT_MASTER = 'GET_EQUIPMENT_MASTER';
export const GET_EQUIPMENT_CATEGORY = 'GET_EQUIPMENT_CATEGORY';
export const GET_EQUIPMENT_TYPE = 'GET_EQUIPMENT_TYPE';
export const GET_EQUIPMENT_SUPPLIER = 'GET_EQUIPMENT_SUPPLIER';
