export const materialHeaderInfo = {
     materialName: "Material",
     materialId : "Id",
     materialcategory : "Category",
     UoM : " UoM",
     unitBaseline : " Unit Baseline Embodied Carbon (kgCO2e)",
     unitDesign : "Unit Design Embodied Carbon (kgCO2e)",
     totalBaseline : " Total Baseline Embodied Carbon (kgCO2e)",
     totalDesignEmbodiedCarbon : "Total Design Embodied Carbon (kgCO2e)",
     quantityRequired : "Qty Required",
     quantityAvailable : " Qty available",
     quantityAssigned : "Qty Assigned",
     quantityConsumed : " Qty consumed",
     type : "Type",
     suppliers : "Suppliers",
     notes : "Notes",
     CUSTOM_TEXT_LENGTH: 10,
     CUSTOM_TEXT_LENGTH_MATERIAL_NAME:25,
}