const { REACT_APP_DEFAULT_LATITUDE, REACT_APP_DEFAULT_LONGITUDE } = process.env;
const DEFAULT_LATITUDE = REACT_APP_DEFAULT_LATITUDE || 37.6597307;
const DEFAULT_LONGITUDE = REACT_APP_DEFAULT_LONGITUDE || -121.8975718;
export { DEFAULT_LATITUDE, DEFAULT_LONGITUDE };
