export abstract class FormTemplates {
    static modelName = 'formTemplates';
    static selector = {
      id: 'id',
      templateName: 'templateName',
      default : 'default',
      featureId: 'featureId',
      createdBy: 'createdBy',
      createdAt: 'createdAt',
      updatedBy: 'updatedBy',
      updatedAt: 'updatedAt',
      firstName: 'firstName',
      lastName: 'lastName',
      templateData: 'templateData',
      affectedRows: 'affected_rows',
      templateId: 'templateId',
      message: 'message',
      formTemplateVersions: 'formTemplateVersions',
      formTemplateFieldData: 'formTemplateFieldData',
      caption: 'caption',
      configListId: 'configListId',
      elementId: 'elementId',
      fieldTypeId: 'fieldTypeId',
      fixed: 'fixed',
      required: 'required',
      sequence: 'sequence',
      templateVersionId: 'templateVersionId',
      width: 'width',
      autoGenerated: 'autoGenerated',
      systemGenerated: 'systemGenerated'
    };
    static relation= {
      formTemplateVersions: 'formTemplateVersions',
      projectFeature: 'projectFeature',
      createdByUser: 'createdByUser',
      updatedByUser: 'updatedByUser',
      formTemplateFieldData: 'formTemplateFieldData'
    };
  }