export interface ProjectLists {
  id: number;
  name: string;
  status: number;
  createdAt: Date;
  address: any;
  config: any;
}
export abstract class FormTemplateModel {
  static modelName = "projectTemplateAssociation";
  static formTemplate = "formTemplate";
  static formTemplateVersions = "formTemplateVersions";
  static formTemplateFieldData = "formTemplateFieldData";
  static workflowEnabled = "workflowEnabled";
  static selector = {
    autoGenerated: "autoGenerated",
    caption: "caption",
    configListId: "configListId",
    elementId: "elementId",
    fieldTypeId: "fieldTypeId",
    fixed: "fixed",
    required: "required",
    metrics: "metrics",
    sequence: "sequence",
    width: "width",
    version: "version",
    id: "id",
    filterable: "filterable",
    tableId: "tableId",
    metadata: "metadata",
  };
}

export abstract class FormStatusModel {
  static modelName = "formStatus";
  static selector = {
    status: "status",
    openStatus: "openStatus",
    id: "id",
    projectFormStatusAssociations: "projectFormStatusAssociations",
    formStatusId: "formStatusId",
  };
}

export abstract class FormTemplateDetailsModel {
  static modelName = "formDetails_query";
  static selector = {
    formState: "formState",
    formsData: "formsData",
    workflowData: "workflowData",
    id: "id",
    templateVersionId: "templateVersionId",
    specificationId: "specificationId",
    blockedByCounter: "blockedByCounter",
    submittalId: "submittalId",
  };
}

export abstract class FormTemplateColumnConfig {
  static modelName = "templateColumnConfiguration";
  static selector = {
    elementId: "elementId",
    fixed: "fixed",
    sequence: "sequence",
  };
}
