export const SPECIFICATION_LIB_DETAILS = "SPECIFICATION_LIB_DETAILS";
export const SPECIFICATION_VERSION_DETAILS = "SPECIFICATION_VERSION_DETAILS";
export const SPECIFICATION_DIVISION_DETAILS = "SPECIFICATION_DIVISION_DETAILS";
export const SPECIFICATION_SECTIONS_DETAILS = "SPECIFICATION_SECTIONS_DETAILS";
export const DISABLE_DIVISIONS_TAB = "DISABLE_DIVISIONS_TAB";
export const DISABLE_SECTIONS_TAB = "DISABLE_SECTIONS_TAB";
export const PARSED_FILE_URL = "PARSED_FILE_URL";
export const IS_AUTO_UPDATE = "IS_AUTO_UPDATE";
export const IS_PUBLISH_DISABLED = "IS_PUBLISH_DISABLED";
export const IS_VERSION_INVALID = "IS_VERSION_INVALID";
export const IS_UPLOAD_OPEN = "IS_UPLOAD_OPEN";
export const PUBLISHED_SPECIFICATION_LIST = "PUBLISHED_SPECIFICATION_LIST";
export const INVALID_VERSION_NAME = "INVALID_VERSION_NAME";
export const INVALID_VERSION_DATE = "INVALID_VERSION_DATE";
export const SECTION_PAGE_NUM = "SECTION_PAGE_NUM";
export const SECTION_PANEL_ARRAY = "SECTION_PANEL_ARRAY";
export const THUMBNAIL_URL = "THUMBNAIL_URL";
export const SPECIFICATION_SHEET_LIST = "SPECIFICATION_SHEET_LIST";
export const SPECIFICATION_LISTS = "SPECIFICATION_LISTS";
export const SPECIFICATION_VIEW = "SPECIFICATION_VIEW";
export const SPECIFICATION_VIEWER_URL = "SPECIFICATION_VIEWER_URL";
export const SUBMITTAL_TRIGGER_RESPONSE = "SUBMITTAL_TRIGGER_RESPONSE";
export const SUBMITTAL_LIB_DETAILS = "SUBMITTAL_LIB_DETAILS";
export const CLOSE_CONFIRM_BOX = "CLOSE_CONFIRM_BOX";
export const SECTION_VIEW = "SECTION_VIEW";
export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const SHOW_FILTER = "SHOW_FILTER";
export const SPEC_SELECTED_FILTER_DATA = "SPEC_SELECTED_FILTER_DATA";
export const SPEC_FILTER_LISTS = "SPEC_FILTER_LISTS";
export const IS_SPEC_FILTER_ON = "IS_SPEC_FILTER_ON";
export const SET_OFFSET = "SET_OFFSET";
export const AUTOGENERATED_NUMBER = "AUTOGENERATED_NUMBER";
export const SUBMITTAL_LIB_LIST = "SUBMITTAL_LIB_LIST";
export const IS_SUBMITTAL_PUBLISH_DISABLED = "IS_SUBMITTAL_PUBLISH_DISABLED";

export const setSpecificationLibDetails = (payload: Array<any>): any => {
  return {
    type: SPECIFICATION_LIB_DETAILS,
    payload,
  };
};

export const setSpecificationVersionDetails = (payload: any): any => {
  return {
    type: SPECIFICATION_VERSION_DETAILS,
    payload,
  };
};

export const setSpecificationDivisionsDetails = (payload: Array<any>): any => {
  return {
    type: SPECIFICATION_DIVISION_DETAILS,
    payload,
  };
};

export const setSpecificationSectionsDetails = (payload: Array<any>): any => {
  return {
    type: SPECIFICATION_SECTIONS_DETAILS,
    payload,
  };
};

export const setDivisionsTabStatus = (payload: boolean): any => {
  return {
    type: DISABLE_DIVISIONS_TAB,
    payload,
  };
};

export const setSectionsTabStatus = (payload: boolean): any => {
  return {
    type: DISABLE_SECTIONS_TAB,
    payload,
  };
};

export const setParsedFileUrl = (payload: any): any => {
  return {
    type: PARSED_FILE_URL,
    payload,
  };
};

export const setThumbnailUrl = (payload: any): any => {
  return {
    type: THUMBNAIL_URL,
    payload,
  };
};
export const setIsAutoUpdate = (payload: boolean): any => {
  return {
    type: IS_AUTO_UPDATE,
    payload,
  };
};

export const setIsPublishDisabled = (payload: boolean): any => {
  return {
    type: IS_PUBLISH_DISABLED,
    payload,
  };
};

export const setVersionValidate = (payload: boolean): any => {
  return {
    type: IS_VERSION_INVALID,
    payload,
  };
};

export const setUploadDialog = (payload: boolean): any => {
  return {
    type: IS_UPLOAD_OPEN,
    payload,
  };
};

export const setPublishedSpecificationLists = (payload: any): any => {
  return {
    type: PUBLISHED_SPECIFICATION_LIST,
    payload,
  };
};

export const setVersionNameValidate = (payload: boolean): any => {
  return {
    type: INVALID_VERSION_NAME,
    payload,
  };
};

export const setVersionDateValidate = (payload: boolean): any => {
  return {
    type: INVALID_VERSION_DATE,
    payload,
  };
};

export const setSectionPageNum = (payload: number): any => {
  return {
    type: SECTION_PAGE_NUM,
    payload,
  };
};
export const setSectionPanelArray = (payload: any): any => {
  return {
    type: SECTION_PANEL_ARRAY,
    payload,
  };
};
export const setSpecificationSheetList = (payload: any): any => {
  return {
    type: SPECIFICATION_SHEET_LIST,
    payload,
  };
};

export const setSpecificationList = (payload: any): any => {
  return {
    type: SPECIFICATION_LISTS,
    payload,
  };
};

export const setSpecificationView = (payload: string): any => {
  return {
    type: SPECIFICATION_VIEW,
    payload,
  };
};
export const setSpecificationViewerUrl = (payload: any): any => {
  return {
    type: SPECIFICATION_VIEWER_URL,
    payload,
  };
};
export const setSubmittalTriggerResponse = (payload: any): any => {
  return {
    type: SUBMITTAL_TRIGGER_RESPONSE,
    payload,
  };
};
export const setSubmittalLibDetails = (payload: Array<any>): any => {
  return {
    type: SUBMITTAL_LIB_DETAILS,
    payload,
  };
};
export const setConfirmBoxStatus = (payload: boolean): any => {
  return {
    type: CLOSE_CONFIRM_BOX,
    payload,
  };
};
export const setSectionView = (payload: any): any => {
  return {
    type: SECTION_VIEW,
    payload,
  };
};
export const setToggleFilter = (payload: boolean): any => {
  return {
    type: TOGGLE_FILTER,
    payload,
  };
};
export const setShowFilter = (payload: boolean): any => {
  return {
    type: SHOW_FILTER,
    payload,
  };
};
export const setSelectedSpecFilterData = (payload: any): any => {
  return {
    type: SPEC_SELECTED_FILTER_DATA,
    payload,
  };
};

export const setIsSpecFilterOn = (payload: boolean): any => {
  return {
    type: IS_SPEC_FILTER_ON,
    payload,
  };
};
export const setSpecFilterList = (payload: any): any => {
  return {
    type: SPEC_FILTER_LISTS,
    payload,
  };
};
export const setOffset = (payload: any): any => {
  return {
    type: SET_OFFSET,
    payload,
  };
};
export const setAutogeneratedNumber = (payload: any): any => {
  return {
    type: AUTOGENERATED_NUMBER,
    payload,
  };
};
export const setSubmittalList = (payload: any): any => {
  return {
    type: SUBMITTAL_LIB_LIST,
    payload,
  };
};

export const setIsSubmittalPublishDisabled = (payload: any): any => {
  return {
    type: IS_SUBMITTAL_PUBLISH_DISABLED,
    payload,
  };
};
