import { Action } from "../../../../models/context";
import { stateContext } from "../../../root/context/authentication/authContext";
import {
    DISABLE_DIVISIONS_TAB, DISABLE_SECTIONS_TAB, SPECIFICATION_DIVISION_DETAILS,
    SPECIFICATION_LIB_DETAILS, SPECIFICATION_SECTIONS_DETAILS,
    SPECIFICATION_VERSION_DETAILS,
     IS_AUTO_UPDATE, 
        IS_PUBLISH_DISABLED, 
        PARSED_FILE_URL,
        IS_VERSION_INVALID,
        IS_UPLOAD_OPEN,
        PUBLISHED_SPECIFICATION_LIST,
        INVALID_VERSION_NAME,
        INVALID_VERSION_DATE,
        SECTION_PAGE_NUM,
        SECTION_PANEL_ARRAY,
        THUMBNAIL_URL,
        SPECIFICATION_SHEET_LIST,
        SPECIFICATION_LISTS,
        SPECIFICATION_VIEW,
        SPECIFICATION_VIEWER_URL,
        SUBMITTAL_TRIGGER_RESPONSE,
        SUBMITTAL_LIB_DETAILS,
        CLOSE_CONFIRM_BOX,
        SECTION_VIEW,
        TOGGLE_FILTER,
        SHOW_FILTER,
        SPEC_FILTER_LISTS,
       SPEC_SELECTED_FILTER_DATA,
        IS_SPEC_FILTER_ON,
        SET_OFFSET,
        AUTOGENERATED_NUMBER,
        SUBMITTAL_LIB_LIST,
        IS_SUBMITTAL_PUBLISH_DISABLED
} from "./SpecificationLibDetailsAction";

export const SpecificationLibDetailsInitialState = {
    specificationLibDetails: [],
    specificationVersionDetails: null,
    specificationDivisionDetails: null,
    specificationSectionsDetails: null,
    divisionsTabStatus: true,
    sectionsTabStatus: true,
     parsedFileUrl: null,
    isAutoUpdate: false,
    isPublishDisabled: true,
    isVersionInValid: true,
    isUploadFileZoneOpen: false,
    publishedSpecificationLists : [],
    isInvalidVersionName: false,
    isInvalidVersionDate: false,
    sectionPageNum: 0,
    sectionPanelArray: [],
    thumbnailUrl:null,
    specificationSheetLists : [],
    specificationLists: [],
    specificationView : 'list',
    specificationViewerFileUrl: [],
    submittalTriggerResponse:null,
    submittalLibDetails: [],
    isConfirmOpen: false,
    sectionView: null,
    toggleFilter: false,
    showFilter: false,
    specFilterList:[],
    selectedSpecFilterData: {
        versionName: [],
        versionDate: [],
    },
    isSpecFilterOn: false,
    offset: 0,
    autoGeneratedNumber:0,
    submittalList: [],
    isSubmittalPublishDisabled: true
}

export const SpecificationLibDetailsReducer = (state: any = SpecificationLibDetailsInitialState, action: Action): any => {
    switch (action.type) {
        case SPECIFICATION_LIB_DETAILS: {
            return {
                ...state,
                specificationLibDetails: action.payload
            }
        }
        case SPECIFICATION_VERSION_DETAILS: {
            return {
                ...state,
                specificationVersionDetails: action.payload
            }
        }
        case SPECIFICATION_DIVISION_DETAILS: {
            return {
                ...state,
                specificationDivisionDetails: action.payload
            }
        }
        case SPECIFICATION_SECTIONS_DETAILS: {
            return {
                ...state,
                specificationSectionsDetails: action.payload
            }
        }
        case DISABLE_DIVISIONS_TAB: {
            return {
                ...state,
                divisionsTabStatus: action.payload
            }
        }
        case DISABLE_SECTIONS_TAB: {
            return {
                ...state,
                sectionssTabStatus: action.payload
            }
        }
        case PARSED_FILE_URL:{
            return {
                ...state,
                parsedFileUrl: action.payload
            }
        }
        case IS_AUTO_UPDATE:{
            return {
                ...state,
                isAutoUpdate: action.payload
            }
        }
        case IS_PUBLISH_DISABLED:{
            return {
                ...state,
                isPublishDisabled: action.payload
            }
        }
        case IS_VERSION_INVALID:{
            return {
                ...state,
                isVersionInValid: action.payload
            }
        }
        case IS_UPLOAD_OPEN:{
            return {
                ...state,
                isUploadFileZoneOpen: action.payload
            }
        }
        case PUBLISHED_SPECIFICATION_LIST:{
            return {
                ...state,
                publishedSpecificationLists: action.payload
            }
        }
        case INVALID_VERSION_NAME:{
            return {
                ...state,
                isInvalidVersionName: action.payload
            }
        }
        case INVALID_VERSION_DATE:{
            return {
                ...state,
                isInvalidVersionDate: action.payload
            }
        }
        case SECTION_PAGE_NUM:{
            return {
                ...state,
                sectionPageNum: action.payload
            }
        }
        case SECTION_PANEL_ARRAY:{
           return{
                ...state,
            sectionPanelArray: action.payload
           }
        }
        case THUMBNAIL_URL:{
            return {
                ...state,
                thumbnailUrl: action.payload
            }
        }
         case SPECIFICATION_SHEET_LIST:{
            return {
                ...state,
                specificationSheetLists: action.payload
            }
        }
        case SPECIFICATION_LISTS:{
            return {
                ...state,
                specificationLists: action.payload
            }
        }
        case SPECIFICATION_VIEW:{
            return {
                ...state,
                specificationView: action.payload
            }
        }
        case SPECIFICATION_VIEWER_URL:{
            return {
                ...state,
                specificationViewerFileUrl: action.payload
            }
        }
         case SUBMITTAL_TRIGGER_RESPONSE:{
            return {
                ...state,
                submittalTriggerResponse: action.payload
            }
        }
         case SUBMITTAL_LIB_DETAILS: {
            return {
                ...state,
                submittalLibDetails: action.payload
            }
        }
        case CLOSE_CONFIRM_BOX: {
            return {
                ...state,
                isConfirmOpen: action.payload
            }
        }
         case SECTION_VIEW: {
            return {
                ...state,
                sectionView: action.payload
            }
        }
        case TOGGLE_FILTER: {
            return {
                ...state,
                toggleFilter: action.payload
            }
        }
        case SHOW_FILTER: {
            return {
                ...state,
                showFilter: action.payload
            }
        }
        case SPEC_SELECTED_FILTER_DATA: {
            return {
                ...state,
                selectedSpecFilterData: action.payload
            }
        }
         case SPEC_FILTER_LISTS: {
            return {
                ...state,
                specFilterList: action.payload
            }
        }
        case IS_SPEC_FILTER_ON: {
            return {
                ...state,
                isSpecFilterOn: action.payload
            }
        }
        case SET_OFFSET: {
            return {
                ...state,
                offset: action.payload
            }
        }
        case AUTOGENERATED_NUMBER: {
            return {
                ...state,
                autoGeneratedNumber: action.payload
            }
        }
        case SUBMITTAL_LIB_LIST: {
            return {
                ...state,
                submittalList: action.payload
            }
        }

        case IS_SUBMITTAL_PUBLISH_DISABLED: {
            return {
                ...state,
                isSubmittalPublishDisabled: action.payload
            }
        }
        
        default: return state
    }
}