
export interface FormFieldData{
    autoGenerated: boolean;
    caption: string;
    configListId: any;
    elementId: string;
    fieldTypeId: number;
    fixed: boolean;
    required: boolean;
    sequence: number;
    width: number;
    tableId: string;
    metaData:any;
    tableFields?:any;
    filterable?: any;
}
